name: Build and test

on: [push, pull_request]

env:
  DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer

jobs:
  build:
    name: Build and test
    runs-on: macOS-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_11.3.1.app/Contents/Developer

    steps:
    - uses: actions/checkout@v1

    - name: Resolve dependencies
      run: xcodebuild -resolvePackageDependencies

    - name: Build
      run: set -o pipefail && xcodebuild -project Whirligig.xcodeproj -scheme Whirligig build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination "platform=iOS Simulator,name=iPhone 11 Pro" | xcpretty --color
