name: Build

on: [push, pull_request]

jobs:
  build:
    name: Test
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1

    - name: Resolve dependencies
      run: xcodebuild -resolvePackageDependencies

    - name: Test data load
      run: set -o pipefail && xcodebuild -project Whirligig.xcodeproj -scheme Whirligig clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination "platform=iOS Simulator,name=iPhone 11 Pro" | xcpretty --color
